### DISCUSSION TITLE
How to use new CIB seven Webapps in a springboot project

### DISCUSSION THREAD

**Discussion by amardeep2006** [cibseven/discussions#9] [Q&A]
I have added following dependency in my springboot project but new webapps does not seem available. I can see the classic camunda webapps.

```xml
    <dependency>
      <groupId>org.cibseven.bpm.springboot</groupId>
      <artifactId>cibseven-bpm-spring-boot-starter-webapp</artifactId>
    </dependency>
```

I downloaded CIBSeven Tomcat version and it opens new webapps but default. Is there some extra setup required for it to work?
It tried this url and  see a white screen only.
http://localhost:8080/webapp/#/seven/auth/start

I assume some extra setup is required for this to work. Please let me know if someone knows the steps/documentation. 
Thanks a lot.

**Comment by amardeep2006** [comment]
I was able to enable this by reading Camunda Run source code and configurations of CIBSeven Run. Had to create a new Filter to add "org.cibseven.bpm.engine.rest.security.auth.impl.CompositeAuthenticationProvider" filter , cibseven.webclient configurations and had to create cibseven-webclient.properties .

One thing still does not feel good to me for dockerised environment . Seems like we need to create cibseven-webclient.properties/cibseven-webclient.yaml via some shell script while starting the docker container. For security reasons, it will prefer to read it via env variables. Let me try if that is possible ?
Just scratching my head on what is the use of following in application.yaml , am i missing something very obvious ?

```yaml
cibseven:
  webclient:
    # Token generation
    authentication:
      jwtSecret:
```

**Reply by PascalLugon** [reply]
Hello,
Could you be more explicit about how you fixed the CIB7 Webapps blank screen?
BR
Pascal

**Reply by amardeep2006** [reply]
I donot have a sample code ready but will publish in a day or two.
High level steps are below:
1. Add a new http filter in your code for engine-rest . You can refer this https://github.com/cibseven/cibseven/blob/main/distro/run/core/src/main/java/org/cibseven/bpm/run/CamundaBpmRunRestConfiguration.java
2. Add the webclient related properties in you application.yml https://github.com/cibseven/cibseven/blob/384372d81c9aa93776680c87cbe3c4ac4a5fe715/distro/run/assembly/resources/default.yml#L50
Make sure you generate a Generate a 155-character alphanumeric random string and set it as jwt secret (DONOT checkin the secret)
```yaml
cibseven:
  webclient:
    authentication:
      jwtSecret: h0tzLJ65jN4gdAeBj5nx78rqKYvqqZswZlP4k2TV218JbHD8kUf6R5HpP4fHDzd2ZbO3f53COn9OmUMnr7Qwhkb3roySoSOgt0bEFhEenCrJfqX043PVRcvsk8v9K3Wprf0NwfJXuPDKAvZnT9jhVE88888
```
3. Create a cibseven-webclient.properties in src/main/resources folder. Make sure this property file has the same 155 character string you generated in last step. Example :
`cibseven.webclient.authentication.jwtSecret=h0tzLJ65jN4gdAeBj5nx78rqKYvqqZswZlP4k2TV218JbHD8kUf6R5HpP4fHDzd2ZbO3f53COn9OmUMnr7Qwhkb3roySoSOgt0bEFhEenCrJfqX043PVRcvsk8v9K3Wprf0NwfJXuPDKAvZnT9jhVE88888`

In the real world scenarios, you may want to generate and set via some shell scripts and add cibseven-webclient.properties into class path. 

I have raised issues as ideally it should all configurable via single yaml and env variable.

**Reply by PascalLugon** [reply]
Amar,
Thx for the different references and indications. I will try to integrate them in my current app.
BR
Pascal

**Reply by amardeep2006** [reply]
I did some more research and in spring boot app and here is what you need to make it work.
1. Without securing /engine-rest , you need to add following in your application.yml

```yaml
cibseven:
  webclient:
    authentication:
      jwtSecret: ***********
    services:
      basePath: /webapp/services/v1
```

3. When you want to secure /engine-rest enfpoint as well.
a. Add a REST security filter and create a cibseven-webclient.properties in src/main/resources and add cibseven.webclient.authentication.jwtSecret=********
b.  Add following to your application.yml 

```yaml
cibseven:
  webclient:
    services:
      basePath: /webapp/services/v1
```
I feel following must be improved in CIB Seven
1. Default basePath must be set to  /webapp/services/v1
2. The composite filter must read values form application.yml for jwtSecret 

I have published a hello world type example on github  .


Unsecured engine-rest example : https://github.com/amardeep2006/cibseven-springboot-example/tree/feat/unsecured-engine-rest

Main Branch has engine-rest secured example :  https://github.com/amardeep2006/cibseven-springboot-example
